### Character based 1-hot encoding (toy example) - Using Keras

    Here we get 2D tensor - merely records if a character is there or not
    A 3D tensor like one in 02_Text 
    
    This one treats bag of characters, while 04 treats a sequence of characters

In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
from keras.preprocessing.text import Tokenizer
import numpy as np

c:\users\a00439512\appdata\local\continuum\anaconda3\envs\demo\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [10]:
sample_set = ['the cat sat on the mat.', 'The dog is eating food', 'ttttttttttttttttttttttt']

In [11]:
print(len(set(sample_set[0])))
print(set(sample_set[0]))
print("\n")
print(len(set(sample_set[1])))
print(set(sample_set[1]))

11
{'n', '.', 'e', 't', 's', 'a', 'm', ' ', 'h', 'o', 'c'}


13
{'T', 'n', 'i', 'e', 'd', 'g', 't', 's', 'f', 'a', ' ', 'h', 'o'}


In [12]:
tokenizer = Tokenizer(num_words=10, char_level=True)

In [13]:
tokenizer.fit_on_texts(sample_set)


In [14]:
seqs = tokenizer.texts_to_matrix(sample_set)

In [17]:
print(type(seqs))
print(len(seqs))

print(len(seqs[0]))
print(len(seqs[1]))


print(seqs[0])
print(seqs[1])
print(seqs[2])

<class 'numpy.ndarray'>
3
10
10
[0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
[0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


In [18]:
print(seqs.shape)

(3, 10)


In [19]:
tokenizer.word_index

{' ': 2,
 '.': 14,
 'T': 15,
 'a': 4,
 'c': 12,
 'd': 9,
 'e': 3,
 'f': 16,
 'g': 10,
 'h': 6,
 'i': 11,
 'm': 13,
 'n': 8,
 'o': 5,
 's': 7,
 't': 1}