# Ch2 of TF book by BR and RBZ

In [4]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [5]:
import tensorflow as tf
import numpy as np

c:\users\a00439512\appdata\local\continuum\anaconda3\envs\demo\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


-----------

In [7]:
# Since we are experimenting, we will use TensorFlow interactively
# load interactive session

tf.InteractiveSession()

1.1
    + Its all about tensors
    + Declare tensors as variables and or feed them in as placeholders

### Basics

In [93]:
a = tf.zeros([2,2]) #default dtype is tf.float32


In [94]:
print(a) # "zeros:i" is an TF's internal naming scheme. every tensor has a name

Tensor("zeros_4:0", shape=(2, 2), dtype=float32)


In [95]:
a.shape

TensorShape([Dimension(2), Dimension(2)])

In [96]:
# TensorFlow returns a reference to the desired tensor rather than the value of the tensor itself. 
# To force the value of the tensor to be returned, we will use the method tf.Tensor.eval() of tensor objects

a.eval()

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [17]:
# output of evaluating a tensor is numpy ndarray

a_ = a.eval() 
print(a_)
type(a_)

[[0. 0.]
 [0. 0.]]


numpy.ndarray

In [16]:
b = tf.zeros([2,2], dtype=tf.int32)
print(b)
b.eval()

Tensor("zeros_3:0", shape=(2, 2), dtype=int32)


array([[0, 0],
       [0, 0]])

In [ ]:
# fixed tensors
c = tf.zeros([2,2])
d = tf.ones([2,2])
e = tf.zeros_like(c)
f = tf.ones_like(d)

g = tf.constant([2,3,4])
h = tf.fill([2,2], 42)

In [105]:
# a.assign(tf.ones([2,2]))


# tensor obj
a = tf.assign(ref=a, value=tf.ones([2,2]))

AttributeError: 'Tensor' object has no attribute 'assign'

## Sampling Random Tensors

In [19]:
# sample from a normal distribution

i = tf.random_normal(shape=[2,2], mean=2.0, stddev=0.5)


In [20]:
#sample from a uniform distribution

j = tf.random_uniform([2,2], minval=4., maxval=8.)

In [ ]:
# sample from a normal distribution
k = tf.truncated_normal([2,2], mean=2., stddev=0.5 )

## Tensor adding, scaling etc


In [21]:
## Tensor adding, scaling etc

l = tf.ones([2,2])
m = tf.ones([2,2])

n = l+m

n.eval()

array([[2., 2.],
       [2., 2.]], dtype=float32)

In [24]:
o = 2 * n # this is scalar multiplication
o.eval()

array([[4., 4.],
       [4., 4.]], dtype=float32)

In [25]:
nn = l * m # element wise multiplication
nn.eval()

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [ ]:
## sequence 

In [33]:
aaa = tf.lin_space(3.,6.,10)
aaa.eval()

array([3.       , 3.3333333, 3.6666667, 4.       , 4.3333335, 4.666667 ,
       5.       , 5.3333335, 5.666667 , 6.       ], dtype=float32)

In [36]:
bbb = tf.range(3.,60.,10)
bbb.eval()

array([ 3., 13., 23., 33., 43., 53.], dtype=float32)

## Matrix Operations

In [29]:
aa = tf.eye(3)
aa.eval()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [39]:
bb = tf.lin_space(3.,6.,3)
bb.eval()

array([3. , 4.5, 6. ], dtype=float32)

In [40]:
aa.shape

TensorShape([Dimension(3), Dimension(3)])

In [41]:
bb.shape

TensorShape([Dimension(3)])

In [44]:
bb  = tf.expand_dims(bb, )
bb.shape

ValueError: Tried to convert 'dim' to a tensor and failed. Error: None values not supported.

In [43]:
cc = tf.matmul(aa, bb)

ValueError: Shape must be rank 2 but is rank 1 for 'MatMul_1' (op: 'MatMul') with input shapes: [3,3], [3].

In [48]:
dd = tf.fill([3,1], 4.2)

In [49]:
ee = tf.matmul(aa,dd)

In [50]:
ee.eval()

array([[4.2],
       [4.2],
       [4.2]], dtype=float32)

In [51]:
eee = tf.matmul(dd,aa)

ValueError: Dimensions must be equal, but are 1 and 3 for 'MatMul_4' (op: 'MatMul') with input shapes: [3,1], [3,3].

## Tensor Types

In [52]:
a = tf.ones((2,2), dtype=tf.int32)
a.eval()

array([[1, 1],
       [1, 1]])

In [54]:
b = tf.to_float(a)
b.eval()

array([[1., 1.],
       [1., 1.]], dtype=float32)

## Tensor Shape Manipulations

In [56]:
aa = tf.ones(8)
aa.eval()

array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [59]:
aa.shape

TensorShape([Dimension(8)])

In [60]:
bb = tf.reshape(aa, (-1,1))

In [62]:
bb.eval()

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)

In [63]:
bb.shape

TensorShape([Dimension(8), Dimension(1)])

In [64]:
cc = tf.reshape(bb, (1,-1))

In [65]:
cc.eval()

array([[1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

In [66]:
cc.shape

TensorShape([Dimension(1), Dimension(8)])

In [73]:
c_ = tf.expand_dims(cc, axis=2) #adds a dimension along the axis specified
c_.shape

TensorShape([Dimension(1), Dimension(8), Dimension(1)])

In [74]:
d_ = tf.squeeze(c_) # removes all dimensions = 1
d_.shape

TensorShape([Dimension(8)])

## Introduction to Broadcasting

In [75]:
aa = tf.ones([2,2])
bb = tf.ones([2])

In [77]:
print(aa.shape)
print(bb.shape)

(2, 2)
(2,)


In [78]:
cc = aa + bb

In [80]:
print(cc.eval())
cc.shape

[[2. 2.]
 [2. 2.]]


TensorShape([Dimension(2), Dimension(2)])

In [ ]:
# Unlike languages like C, TensorFlow doesn’t perform implicit type casting under the hood.

In [81]:
b = tf.range(0, 2, 1)

In [82]:
aa + b

ValueError: Tensor conversion requested dtype float32 for Tensor with dtype int32: 'Tensor("range_5:0", shape=(2,), dtype=int32)'

# TensorFlow Graphs

In [83]:
# note we never specified a Graph() object. So all tensors got appended to default graph. 
# We can access default graph 

g = tf.get_default_graph()


# TensorFlow Sessions

In [ ]:
# tf.Session() object stores the context under which a computation is performed

In [85]:
# way 1

sess = tf.Session()

a = tf.ones([2,2])
b = tf.ones([2,2])

c = a + b

c.eval(session=sess)

array([[2., 2.],
       [2., 2.]], dtype=float32)

In [86]:
# way 2

sess1 = tf.Session()

a = tf.ones([2,2])
b = tf.ones([2,2])

c = a+b

sess.run(c)

array([[2., 2.],
       [2., 2.]], dtype=float32)

In [ ]:
# calling c.eval(session=sess) is just syntactic sugar for calling sess.run(c).

## TensorFlow Variables

In [87]:
# All the  code  used until now constant tensors. 

var = tf.Variable(tf.ones([2,2]))

In [88]:
var

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32_ref>

In [89]:
var.eval()

FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[Node: _retval_Variable_0_0 = _Retval[T=DT_FLOAT, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Variable)]]

In [91]:
sess = tf.Session()
init_op = tf.global_variables_initializer()

sess.run(init_op)

In [92]:
sess.run(var)

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [ ]:
# The shape of the variable is fixed upon initialization and must be preserved with updates.

In [101]:
# update value of variablae

var = var.assign(tf.zeros([2,2]))

In [102]:
sess.run(var)

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [103]:
var = tf.assign(ref=var, value=tf.ones([2,2]))

In [104]:
sess.run(var)

array([[1., 1.],
       [1., 1.]], dtype=float32)