# Ch1 from the book McClure 

In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import tensorflow as tf
import numpy as np

1.1
    + Its all about tensors
    + Declare tensors as variables and or feed them in as placeholders

In [4]:
# Since we are experimenting, we will use TensorFlow interactively

tf.InteractiveSession()

In [5]:
a = tf.zeros([3,4])

In [6]:
# TensorFlow returns a reference to the desired tensor rather than the value of the tensor itself. 
# To force the value of the tensor to be returned, we will use the method tf.Tensor.eval() of tensor objects

a.eval()

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [7]:
a.shape

TensorShape([Dimension(3), Dimension(4)])

In [8]:
a = tf.zeros(2)
a.eval()

array([0., 0.], dtype=float32)

In [13]:
a = tf.zeros(2, dtype=tf.int32)
a.eval()

array([0, 0], dtype=int32)

In [3]:
# fixed tensors

a = tf.zeros([3,4])
b = tf.ones([2,3])
c = tf.zeros_like(a)
d = tf.ones_like(b)