In [1]:
# Config the matlotlib backend as plotting inline in IPython
#%matplotlib inline
%load_ext autoreload
%autoreload 2

In [2]:
# start afresh
# book TF ML cookbook by Nick McClure

In [3]:
import tensorflow as tf

### create some basic tensors

In [14]:
# fixed tensors

zero_tsr = tf.zeros([3,3])
one_tsr = tf.ones([4,4])

In [15]:
filled_tsr = tf.fill([5,5], 42)

In [16]:
constant_tsr = tf.constant([1,2,3])

In [17]:
sess = tf.Session()
init_op = tf.global_variables_initializer()
sess.run(init_op)

In [18]:
zero_tsr.eval(session=sess)


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [19]:
one_tsr.eval(session=sess)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [20]:
filled_tsr.eval(session=sess)

array([[42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42]], dtype=int32)

In [21]:
constant_tsr.eval(session=sess)

array([1, 2, 3], dtype=int32)

In [ ]:
# tensors with similar shape

In [ ]:
zero_similar = tf.zeros_like(zero_tsr)
one_similar = tf.ones_like(one_tsr)

In [ ]:
#sequence tensors

In [ ]:
linear_tsr = tf.linspace(start=0.0, stop=5.0, num=5)

In [ ]:
integer_seq = tf.range(start=6, limit=12, delta=3)

In [ ]:
# random tensors

In [ ]:
random_tsr = tf.random_uniform([5,4], minval=0.0, maxval=1.0)

In [ ]:
random_tsr = tf.random_normal([5,4], mean=0.0, stddev=1.0)

In [ ]:
random_tsr = tf.truncated_normal([5,4], mean=0.0, stddev=1.0)

In [ ]:
shuffled_output = tf.random_shuffle(input_tsr)
tf.random_crop(input_tensor, [dim1, dim2, dim3])

### creating variables

In [ ]:
# takes a tensor and returns a variable
my_var = tf.Variable(zero_similar)

In [ ]:
# convert numpy lists into tensor
ll = [1,2,3]

ll1 = tf.convert_to_tensor(ll)

In [ ]:
# variable vs placeholder
# variable has data
# placeholder gets data at runtime - just need type and shape


In [ ]:
my_var = tf.Variable(tf.zeros([2,3]))

sess = tf.Session()
initialize_op = tf.global_variables_initializer() # initializes all variables not tensors. tensors are 

sess.run(initialize_op)

In [ ]:
my_var.eval()

In [ ]:
import numpy as np

sess = tf.Session()

x = tf.placeholder(tf.float32, shape=[2,2])
y = tf.identity(x)

x_vals = np.random.rand(2,2)

sess.run(y, feed_dict={x:x_vals})


In [ ]:
sess = tf.Session()
first_var = tf.Variable(tf.zeros([2,3]))
sess.run(first_var.initializer)
#first_var.eval()
second_var = tf.Variable(tf.zeros_like(first_var))
print(sess.run(second_var.initializer))
print(type(first_var))

In [ ]:
identity_matrix = tf.diag([1.0, 1.0, 1.0])
print(sess.run(identity_matrix))

In [ ]:
type(identity_matrix)

In [ ]:
# KEY point - you can print a tensor not a variable !!

In [ ]:
print(sess.run(tf.nn.relu([-3, 3, 10])))

In [ ]:
print(sess.run(tf.nn.sigmoid([-10.0, 3.0, 10.0])))

In [ ]:
# load some datasets

In [9]:
from sklearn import datasets

iris = datasets.load_iris()

print len(iris.data)

print(len(iris.target))

print((iris.target[0]))

print((iris.data[0]))

print(set(iris.target))

150
150
0
[5.1 3.5 1.4 0.2]
set([0, 1, 2])


In [14]:
import requests

birthdata_url = 'https://www.umass.edu/statdata/statdata/data/lowbwt.data'
birth_file = requests.get(birthdata_url)

birth_data = birth_file.text.split('\r\n')[5:]

print birth_data

[]
