In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
#from keras import layers, models
from keras.datasets import mnist
import numpy as np

c:\users\a00439512\appdata\local\continuum\anaconda3\envs\demo\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


# load dataset

In [3]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [4]:
print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)



(60000, 28, 28)
(10000, 28, 28)
(60000,)
(10000,)


In [5]:
print(type(X_train))
print(type(y_train))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [6]:
print(type(X_train[0]))
print(X_train[0].shape)

print(type(X_train[0][0]))
print(type(X_train[0][0][0]))

print(X_train[0])

<class 'numpy.ndarray'>
(28, 28)
<class 'numpy.ndarray'>
<class 'numpy.uint8'>
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3  18  18  18 126 136
  175  26 166 255 247 127   0   0   0   0]
 [  0   0   0   0   0   0   0   0  30  36  94 154 170 253 253 253 253 253
  225 172 253 242 195  64   0   0   0   0]
 [  0   0   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251
   93  82  82  56  39   0   

# Format dataset in correct shape

In [7]:
X_train = X_train.reshape(-1, 28*28)
X_test = X_test.reshape(-1, 28*28)

print(X_train.shape)
print(X_test.shape)

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

X_train = X_train/255
X_test = X_test/255

(60000, 784)
(10000, 784)


In [8]:
print(type(X_train[0]))
print(X_train[0].shape)

print(type(X_train[0][0]))
#print(type(X_train[0][0][0]))

print(X_train[0])

<class 'numpy.ndarray'>
(784,)
<class 'numpy.float32'>
[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 

In [9]:
from keras.utils import to_categorical

In [10]:
print(np.unique(y_train))
print(np.unique(y_test))

print(y_train[:5])
print(y_test[:5])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[5 0 4 1 9]
[7 2 1 0 4]


In [11]:
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [12]:
print(np.unique(y_train))
print(np.unique(y_test))

print(y_train[:5])
print(y_test[:5])

[0. 1.]
[0. 1.]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


# Build a basic netwrok

In [13]:
from keras.models import Sequential
from keras.layers import Dense

In [18]:
model = Sequential()
model.add(Dense(512, activation='relu', input_shape=(28*28,)))
model.add(Dense(10, activation='softmax'))

In [19]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model

In [20]:
history = model.fit(X_train, y_train, epochs=5, batch_size=32)

Epoch 1/5
60000/60000 [==============================] - 18s 308us/step - loss: 0.0344 - acc: 0.9884
Epoch 2/5
60000/60000 [==============================] - 17s 282us/step - loss: 0.0147 - acc: 0.9951
Epoch 3/5
60000/60000 [==============================] - 16s 272us/step - loss: 0.0099 - acc: 0.9967
Epoch 4/5
60000/60000 [==============================] - 17s 286us/step - loss: 0.0073 - acc: 0.9975
Epoch 5/5
60000/60000 [==============================] - 16s 271us/step - loss: 0.0055 - acc: 0.9982


In [22]:
(test_loss, test_accuracy) = model.evaluate(X_test, y_test)
print(test_loss)
print(test_accuracy)

10000/10000 [==============================] - 1s 69us/step
0.013999633967231785
0.9955599971771241
